"""
AgentVault CLI

Usage:
    agentvault status   <agent_name>
    agentvault history  <agent_name> [--limit N]
    agentvault reset    <agent_name>
    agentvault init

Reads AGENTVAULT_DATA_DIR from .env (default: ./data).
"""

import argparse
import os
import sys
from datetime import datetime, timezone

from dotenv import load_dotenv

load_dotenv()


def _data_dir() -> str:
    return os.getenv("AGENTVAULT_DATA_DIR", "./data")


def _get_storage(agent_name: str):
    from agentvault.storage import Storage
    safe = agent_name.replace("/", "_").replace(" ", "_")
    path = os.path.join(_data_dir(), f"{safe}.db")
    if not os.path.exists(path):
        print(f"❌  Agent '{agent_name}' not found in {_data_dir()}/")
        sys.exit(1)
    return Storage(path)


def cmd_status(args) -> None:
    """Show current status of an agent."""
    from agentvault.rules import get_period_start, compute_spent

    storage = _get_storage(args.agent_name)
    state = storage.load()

    now = datetime.now(timezone.utc)
    period_start = get_period_start(state["period"], now)
    spent = compute_spent(state["transactions"], period_start)
    remaining = round(state["budget_usdc"] - spent, 6)
    cb = state["circuit_breaker"]

    print(f"\n{'─' * 44}")
    print(f"  AgentVault — {state['agent_name']}")
    print(f"{'─' * 44}")
    print(f"  Budget         {state['budget_usdc']:.2f} USDC / {state['period']}")
    print(f"  Spent          {spent:.2f} USDC")
    print(f"  Remaining      {remaining:.2f} USDC")
    print(f"  Max / tx       {state['max_per_tx']:.2f} USDC")
    print(f"  Whitelist      {len(state['whitelist'])} address(es)")
    print(f"  Total tx       {len(state['transactions'])}")

    cb_status = "🔴 TRIPPED" if cb["tripped"] else "🟢 OK"
    print(f"  Circuit BK     {cb_status}")
    if cb["tripped"] and cb["tripped_at"]:
        print(f"  Tripped at     {cb['tripped_at'][:19]} UTC")

    if state["created_at"]:
        print(f"  Created at     {state['created_at'][:19]} UTC")
    print(f"{'─' * 44}\n")


def cmd_history(args) -> None:
    """Show transaction history of an agent."""
    storage = _get_storage(args.agent_name)
    txs = storage.get_transactions(limit=args.limit)

    if not txs:
        print(f"No transactions found for '{args.agent_name}'.")
        return

    print(f"\n  History — {args.agent_name} (last {len(txs)})")
    print(f"  {'Date':<20} {'Amount':>8}  {'Status':<10}  Reason")
    print(f"  {'─'*20} {'─'*8}  {'─'*10}  {'─'*30}")

    for tx in txs:
        date = tx["timestamp"][:16] if tx["timestamp"] else "?"
        amount = f"{tx['amount']:.2f}"
        status = tx["status"] or "?"
        reason = (tx["reason"] or "")[:40]
        chain_marker = " ⛓" if tx["onchain"] else ""
        print(f"  {date:<20} {amount:>8}  {status:<10}  {reason}{chain_marker}")
    print()


def cmd_reset(args) -> None:
    """Reset the circuit breaker of an agent."""
    storage = _get_storage(args.agent_name)
    state = storage.load()
    cb = state["circuit_breaker"]

    if not cb["tripped"]:
        print(f"ℹ️  Circuit breaker for '{args.agent_name}' is not tripped.")
        return

    confirm = input(
        f"⚠️  Reset circuit breaker for '{args.agent_name}'? [yes/N] "
    ).strip().lower()

    if confirm != "yes":
        print("Cancelled.")
        return

    storage.reset_circuit_breaker()
    print(f"✅  Circuit breaker for '{args.agent_name}' has been reset.")


def cmd_init(args) -> None:
    """Generate a new private key and .env file."""
    try:
        from eth_account import Account
    except ImportError:
        print("❌  web3 required: pip install web3")
        sys.exit(1)

    env_path = os.path.join(os.getcwd(), ".env")

    if os.path.exists(env_path):
        confirm = input(
            f"⚠️  A .env file already exists ({env_path}). Overwrite? [yes/N] "
        ).strip().lower()
        if confirm != "yes":
            print("Cancelled.")
            return

    acc = Account.create()

    env_content = f"""# AgentVault — environment variables
# Auto-generated by: agentvault init
# NEVER commit this file to Git

# Agent wallet private key
AGENT_PRIVATE_KEY={acc.key.hex()}

# Discord webhook for alerts (optional)
DISCORD_WEBHOOK_URL=

# Blockchain network: "base" (mainnet) or "base-sepolia" (testnet)
CHAIN=base-sepolia

# Infura RPC key (optional — fallback if public RPC is unavailable)
# INFURA_API_KEY=

# Agent state storage directory (default: ./data)
# AGENTVAULT_DATA_DIR=./data
"""

    with open(env_path, "w") as f:
        f.write(env_content)

    print(f"\n✅  Wallet generated successfully!")
    print(f"   Address    : {acc.address}")
    print(f"   .env       : {env_path}")
    print(f"\n⚠️  Your private key is in .env — never commit it to Git.")
    print(f"   Make sure .env is in your .gitignore.\n")
    print(f"   Next steps:")
    print(f"   1. Get ETH on Base to pay for gas")
    print(f"   2. Get USDC on Base")
    print(f"   3. Set DISCORD_WEBHOOK_URL for alerts\n")


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="agentvault",
        description="AgentVault — budget controller for AI agents spending USDC on Base",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_status = sub.add_parser("status", help="Show agent status")
    p_status.add_argument("agent_name", help="Agent name")
    p_status.set_defaults(func=cmd_status)

    p_history = sub.add_parser("history", help="Show transaction history")
    p_history.add_argument("agent_name", help="Agent name")
    p_history.add_argument("--limit", type=int, default=20,
                            help="Number of transactions to show (default: 20)")
    p_history.set_defaults(func=cmd_history)

    p_reset = sub.add_parser("reset", help="Reset the circuit breaker")
    p_reset.add_argument("agent_name", help="Agent name")
    p_reset.set_defaults(func=cmd_reset)

    p_init = sub.add_parser("init", help="Generate a private key and .env file")
    p_init.set_defaults(func=cmd_init)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
